### ISSUE TITLE
ImportError: No module named sk1libs.utils.fs

### ISSUE THREAD

**Issue by esguti** [sk1project/uniconvertor#11]
I have properly execute 
```bash
python setup.py build
```

But, when I try to execute:
```bash
python build/scripts-2.7/uniconvertor InkShield-B.Cu.svg InkShield-B.Cu.plt
```

I receive the error:
```bash
Traceback (most recent call last):
  File "build/scripts-2.7/uniconvertor", line 13, in <module>
    uniconv_run()
  File "/usr/lib/python2.7/dist-packages/uniconvertor/__init__.py", line 83, in uniconv_run
    from app.io import load
  File "/usr/lib/python2.7/dist-packages/uniconvertor/app/__init__.py", line 69, in <module>
    from conf.configurator import Configurator
  File "/usr/lib/python2.7/dist-packages/uniconvertor/app/conf/configurator.py", line 11, in <module>
    from app.events import connector
  File "/usr/lib/python2.7/dist-packages/uniconvertor/app/__init__.py", line 69, in <module>
    from conf.configurator import Configurator
  File "/usr/lib/python2.7/dist-packages/uniconvertor/app/conf/configurator.py", line 13, in <module>
    from sk1libs.utils.fs import gethome
ImportError: No module named sk1libs.utils.fs
```

I have:
- Linux Mint 18 64bits
- Python 2.7.12

**Comment by Meloman-zz** [comment]
Have the same issue. Uniconvertor has been installed with apt on Ubuntu 16.04, trying to convert cdr to ai/svg

For me, solution was to install missing library libjpeg-dev (with aptitude)

**Comment by axel-h** [comment]
Installing libjpeg-dev did not work for me.
