### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Legingo** [sk1project/uniconvertor#20]
Uniconvertor version - 2.0 Release Candidate 4
Attempting to convert CCX file to SVG.
These CCX files are very old, late 1990s.
Two test files have been attached.

Traceback (most recent call last):
  File "uniconvertor.py", line 59, in <module>
  File "/home/travis/build/sk1project-build-bot/sk1-wx/src/uc2/__init__.py", line 44, in uc2_run
  File "/vagrant/uniconvertor-2.0rc4-20190525-win64-portable/libs/uc2/application.py", line 219, in run
TypeError: 'NoneType' object is not iterable

[TestFiles.zip](https://github.com/sk1project/uniconvertor/files/4234208/TestFiles.zip)

**Comment by sk1project** [comment]
Try using UniConvertor 2.0rc5 (https://sk1project.net/uc2/daily-builds/) It seem the issue has been fixed half year ago.
![Screenshot from 2020-02-24 22-14-51](https://user-images.githubusercontent.com/13432939/75187645-230a4880-5753-11ea-8350-384abd587a13.png)
