### ISSUE TITLE
cgm: NoneType not iterable

### ISSUE THREAD

**Issue by andreasplesch** [sk1project/uniconvertor#24]
build:python-uniconvertor-2.0rc5_20200706_debian_10_amd64.deb

UniConvertor failed:
ERROR  | Error while translation and saving "/home/andreas/Home/dhome/projects/cfma/gocad/working_projects/BrendanBEM/SectionBext.cgm"
STOP   | Translation is interrupted
For details see logs: /home/andreas/.config/uc2/uc2.log

uc2.log:

```
 INFO     | 12:53:11 PM | uc2.application --> Translation of "/home/andreas/Home/dhome/projects/cfma/gocad/working_projects/BrendanBEM/SectionBex
t.cgm" into "/tmp/tmpmdNhcE.svg"
 INFO     | 12:53:11 PM | uc2.application --> Start to search saver by file extension svg
 INFO     | 12:53:11 PM | uc2.application --> Saver is found for extension svg
 INFO     | 12:53:11 PM | uc2.application --> Start to search for loader by file extension cgm
 INFO     | 12:53:12 PM | uc2.application --> Loader "cgm_loader" is found for /home/andreas/Home/dhome/projects/cfma/gocad/working_projects/Bren
danBEM/SectionBext.cgm
 INFO     | 12:53:12 PM | uc2.application --> Parsing in progress...
 INFO     | 12:53:12 PM | uc2.application --> <CGM> document model is created
 INFO     | 12:53:12 PM | uc2.application --> <CGM> document model is updated successfully
 INFO     | 12:53:12 PM | uc2.application --> <SK2> document model is updated successfully
 INFO     | 12:53:12 PM | uc2.application --> <CGM> document model is destroyed for /home/andreas/Home/dhome/projects/cfma/gocad/working_projects
/BrendanBEM/SectionBext.cgm
 INFO     | 12:53:12 PM | uc2.application --> <SVG> document model is updated successfully
 ERROR    | 12:53:12 PM | uc2.application --> Error while translation and saving "/home/andreas/Home/dhome/projects/cfma/gocad/working_projects/B
rendanBEM/SectionBext.cgm"
 ERROR    | 12:53:12 PM | uc2.cmds.translate --> Error while translation and saving "/home/andreas/Home/dhome/projects/cfma/gocad/working_project
s/BrendanBEM/SectionBext.cgm"
Traceback (most recent call last):
  File "/usr/lib/uniconvertor-2.0rc5/uc2/cmds/translate.py", line 104, in convert
    saver(doc, files[1], **options)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/__init__.py", line 49, in svg_saver
    svg_doc.translate_from_sk2(sk2_doc)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_presenter.py", line 63, in translate_from_sk2
    translator.translate(sk2_doc, self)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_translators.py", line 1141, in translate
    self.translate_page(self.svg_mt, page)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_translators.py", line 1170, in translate_page
    self.translate_objs(self.svg_mt, source_obj.childs)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_translators.py", line 1177, in translate_objs
    self.translate_layer(dest_parent, source_obj)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_translators.py", line 1202, in translate_layer
    self.translate_objs(group, source_obj.childs)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_translators.py", line 1195, in translate_objs
    self.translate_primitive(dest_parent, source_obj)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_translators.py", line 1254, in translate_primitive
    curve = source_obj.to_curve()
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/sk2/sk2_model.py", line 546, in to_curve
    curve.update()
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/sk2/sk2_model.py", line 554, in update
    self.cache_cpath = libgeom.create_cpath(self.cache_paths)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/libgeom/cwrap.py", line 22, in create_cpath
    return libcairo.create_cpath(cache_paths)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/libcairo/__init__.py", line 37, in create_cpath
    for path in paths:
TypeError: 'NoneType' object is not iterable
```
[SectionBext.zip](https://github.com/sk1project/uniconvertor/files/4886131/SectionBext.zip)

**Comment by MihailCosmin** [comment]
For some CGMs I get the same error.

I also get some other errors when trying to convert CGMs:

```
 ERROR    | 09:30:42 AM | uc2.application --> Loading is interrupted float division by zero

 ERROR    | 10:29:56 AM | uc2.application --> Loading is interrupted tuple index out of range
```
