### ISSUE TITLE
CGM -> SVG Conversion Failure

### ISSUE THREAD

**Issue by SukkoPera** [sk1project/uniconvertor#26]
I am experiencing an issue that seems closely related to #24 and #25 when trying to convert a CGM file to SVG:
```
[sukko@reposync testcgm]$ uniconvertor 

UniConvertor 2.0rc5 build 20201217

USAGE: uniconvertor [OPTIONS] [INPUT FILE] [OUTPUT FILE]
Use --help for more details.
For detailed help visit https://sk1project.net/uc2/help/

[sukko@reposync testcgm]$ uniconvertor in.cgm out.svg
ERROR  | Error while translation and saving "/home/sukko/testcgm/in.cgm"
STOP   | Translation is interrupted
For details see logs: /home/sukko/.config/uc2/uc2.log
```

`/home/sukko/.config/uc2/uc2.log` contains the following:
```
 INFO     | 09:20:24 AM | uc2.application --> Translation of "/home/sukko/testcgm/in.cgm" into "/home/sukko/testcgm/out.svg"
 INFO     | 09:20:24 AM | uc2.application --> Start to search saver by file extension svg
 INFO     | 09:20:24 AM | uc2.application --> Saver is found for extension svg
 INFO     | 09:20:24 AM | uc2.application --> Start to search for loader by file extension cgm
 INFO     | 09:20:24 AM | uc2.application --> Loader "cgm_loader" is found for /home/sukko/testcgm/in.cgm
 INFO     | 09:20:24 AM | uc2.application --> Parsing in progress...
 INFO     | 09:20:24 AM | uc2.application --> <CGM> document model is created
 INFO     | 09:20:24 AM | uc2.application --> <CGM> document model is updated successfully
 INFO     | 09:20:24 AM | uc2.application --> <SK2> document model is updated successfully
 INFO     | 09:20:24 AM | uc2.application --> <CGM> document model is destroyed for /home/sukko/testcgm/in.cgm
 INFO     | 09:20:24 AM | uc2.application --> <SVG> document model is updated successfully
 ERROR    | 09:20:24 AM | uc2.application --> Error while translation and saving "/home/sukko/testcgm/in.cgm"
 ERROR    | 09:20:24 AM | uc2.cmds.translate --> Error while translation and saving "/home/sukko/testcgm/in.cgm"
Traceback (most recent call last):
  File "/usr/lib/uniconvertor-2.0rc5/uc2/cmds/translate.py", line 104, in convert
    saver(doc, files[1], **options)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/__init__.py", line 49, in svg_saver
    svg_doc.translate_from_sk2(sk2_doc)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_presenter.py", line 63, in translate_from_sk2
    translator.translate(sk2_doc, self)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_translators.py", line 1141, in translate
    self.translate_page(self.svg_mt, page)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_translators.py", line 1170, in translate_page
    self.translate_objs(self.svg_mt, source_obj.childs)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_translators.py", line 1177, in translate_objs
    self.translate_layer(dest_parent, source_obj)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_translators.py", line 1202, in translate_layer
    self.translate_objs(group, source_obj.childs)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_translators.py", line 1195, in translate_objs
    self.translate_primitive(dest_parent, source_obj)
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/svg/svg_translators.py", line 1254, in translate_primitive
    curve = source_obj.to_curve()
  File "/usr/lib/uniconvertor-2.0rc5/uc2/formats/sk2/sk2_model.py", line 1014, in to_curve
    for item in self.cache_cpath:
TypeError: 'NoneType' object is not iterable
```

The image I'm trying to convert is this one: [in.zip](https://github.com/sk1project/uniconvertor/files/5735889/in.zip)

**Comment by sk1project** [comment]
@SukkoPera Thank you for reported issue. The problem has been fixed. The build with fixes will be four hours later. After that you may fetch fixed version on following link: https://sk1project.net/uc2/daily-builds/

**Comment by SukkoPera** [comment]
I can confirm it's now working fine. Thanks a lot! :)
