### ISSUE TITLE
Bulk conversions with UniConvertor?

### ISSUE THREAD

**Issue by francois072** [sk1project/uniconvertor#35]
Is there anyway to do bulk conversions with UniConvertor?

**Comment by maxim-s-barabash** [comment]
UniConvertor 2.0rc5 build 20210316

```bash
uniconvertor --recursive --format=PDF *.svg ./pdf/
```

**Comment by francois072** [comment]
```
 INFO     | 12:53:23 AM | uc2.application --> Translation of "/run/media/francois/Storage/Pictures/Gnupg_logo.svg" into "./pdf/"
 INFO     | 12:53:23 AM | uc2.application --> Start to search for loader by file extension svg
 INFO     | 12:53:24 AM | uc2.application --> Loader "svg_loader" is found for /run/media/francois/Storage/Pictures/Gnupg_logo.svg
 INFO     | 12:53:24 AM | uc2.application --> <SVG> document model is updated successfully
 INFO     | 12:53:24 AM | uc2.application --> Parsing in progress...
 INFO     | 12:53:24 AM | uc2.application --> <SVG> document model is created
 INFO     | 12:53:24 AM | uc2.application --> <SVG> document model is updated successfully
 INFO     | 12:53:24 AM | uc2.application --> <SK2> document model is updated successfully
 INFO     | 12:53:24 AM | uc2.application --> <SVG> document model is destroyed for /run/media/francois/Storage/Pictures/Gnupg_logo.svg
 INFO     | 12:53:24 AM | uc2.application --> Saving is started...
 ERROR    | 12:53:24 AM | uc2.application --> Cannot open ./pdf/ file for writing
 ERROR    | 12:53:24 AM | uc2.utils.fsutils --> Cannot open ./pdf/ file for writing
 ERROR    | 12:53:24 AM | uc2.formats.generic --> Error while saving ./pdf/ %s
 ERROR    | 12:53:24 AM | uc2.formats.generic --> [Errno 21] Is a directory: u'./pdf/'
Traceback (most recent call last):
  File "/usr/lib/uniconvertor-2.0rc4/uc2/formats/generic.py", line 187, in save
    self.saver.save(self, filename, fileptr)
  File "/usr/lib/uniconvertor-2.0rc4/uc2/formats/generic_filters.py", line 199, in save
    self.fileptr = get_fileptr(path, True)
  File "/usr/lib/uniconvertor-2.0rc4/uc2/utils/fsutils.py", line 64, in get_fileptr
    fileptr = open(path, 'wb')
IOError: [Errno 21] Is a directory: u'./pdf/'
 ERROR    | 12:53:24 AM | uc2.application --> Error while translation and saving "/run/media/francois/Storage/Pictures/Gnupg_logo.svg"
 ERROR    | 12:53:24 AM | uc2.application --> Translation is interrupted [Errno 21] Is a directory: u'./pdf/'
Traceback (most recent call last):
  File "/usr/lib/uniconvertor-2.0rc4/uc2/application.py", line 250, in run
    saver(doc, files[1], **options)
  File "/usr/lib/uniconvertor-2.0rc4/uc2/formats/pdf/__init__.py", line 34, in pdf_saver
    sk2_doc.save(filename, fileptr)
  File "/usr/lib/uniconvertor-2.0rc4/uc2/formats/generic.py", line 187, in save
    self.saver.save(self, filename, fileptr)
  File "/usr/lib/uniconvertor-2.0rc4/uc2/formats/generic_filters.py", line 199, in save
    self.fileptr = get_fileptr(path, True)
  File "/usr/lib/uniconvertor-2.0rc4/uc2/utils/fsutils.py", line 64, in get_fileptr
    fileptr = open(path, 'wb')
IOError: [Errno 21] Is a directory: u'./pdf/'
```
```
[francois@francois-pc Pictures]$ uniconvertor --recursive --format=PDF *.svg ./pdf/
ERROR  | Cannot open ./pdf/ file for writing
ERROR  | Error while translation and saving "/run/media/francois/Storage/Pictures/Gnupg_logo.svg"
STOP   | Translation is interrupted
For details see logs: /home/francois/.config/uc2/uc2.log
```

**Comment by francois072** [comment]
Where is the documentation that has more information than uniconvertor --help?

**Comment by maxim-s-barabash** [comment]
try upgrading to rc5
https://sk1project.net/uc2/daily-builds/

**Comment by francois072** [comment]
That worked!
Thanks

Does uniconvertor support converting from CDR files?

Is it possible to create a Dolphin service menu for uniconvertor so that It's faster and more convenient to convert files in bulk?
