### ISSUE TITLE
ImportError: No module named app.events

### ISSUE THREAD

**Issue by blokhin** [sk1project/uniconvertor#5]
Good day!

I built uniconvertor on Ubuntu from master without errors. But when I'm trying to use it, there's an ImportError:

Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

```
>>> from uniconvertor import app
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "uniconvertor/app/__init__.py", line 69, in <module>
    from conf.configurator import Configurator
  File "uniconvertor/app/conf/configurator.py", line 11, in <module>
    from app.events import connector
ImportError: No module named app.events
```

**Comment by blokhin** [comment]
Resolved. One should pay attention to `__path__` and `sys.path` running uniconvertor in such a way.
